# Generated by Django 4.1.3 on 2022-11-21 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_poketeam_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='poketeam',
            name='publish',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
